### ISSUE TITLE
BUG : display_results.sh doesn't seem to be escaping user input properly

### ISSUE THREAD

**Issue by Zeitsperre** [green-coding-solutions/eco-ci-energy-estimation#89]
Hi, 

I happened upon this project last week and have been seeing what it could look like to integrate this into a somewhat complex CI pipeline I manage. I'm hoping this action might be the push we need to reduce our CI complexity a bit or self-host our own runners. Neat project!

The issue I'm having is that when trying to run `display-results`, it seems as though the input fields of some steps might not be able to handle some special characters (brackets, maybe?). 

Example: https://github.com/Ouranosinc/xclim/actions/runs/10255754010/job/28373433987#step:13:1

Error:
```
Run /home/runner/work/_actions/green-coding-solutions/eco-ci-energy-estimation/7333e9a8e8036e5bf69d59dc8bb63d984b0f55c8/scripts/display_results.sh -dt true -dg true -db true -b "1863/merge" -r 10255754010 -R "Ouranosinc/xclim" -sd true -sc true -s "github"
/home/runner/work/_actions/green-coding-solutions/eco-ci-energy-estimation/7333e9a8e8036e5bf69d59dc8bb63d984b0f55c8/scripts/display_results.sh: eval: line 72: unexpected EOF while looking for matching `"'
```

I imagine this might simply be solved by escaping more of the user input fields.

### Additional Resources
The workflow file (testing branch, being actively worked on): https://github.com/Ouranosinc/xclim/blob/energy-usage/.github/workflows/main.yml

**Comment by Zeitsperre** [comment]
@ribalba That seems to have fixed the issue. Feel free to examine the build logs if you're interested!

I won't be merging my branch until a stable release is made with the fixes.

Thanks!

**Comment by ribalba** [comment]
Pre-Release is here: https://github.com/green-coding-solutions/eco-ci-energy-estimation/releases/tag/v4.0-rc4
Will become stable the next few days.
