### ISSUE TITLE
update-tag.yml still uses an old version of the pipeline

### ISSUE THREAD

**Issue by ribalba** [green-coding-solutions/eco-ci-energy-estimation#92]
in .github/workflows/update-tag.yml

```
    steps:
    - uses: actions/checkout@v3
```
I assume this should be `v4`

**Comment by ArneTR** [comment]
yes. It can just be changed. No issues expected

**Comment by Zeitsperre** [comment]
Why not use Dependabot?

**Comment by ArneTR** [comment]
good call.

https://github.com/green-coding-solutions/eco-ci-energy-estimation/pull/93

will close
